# Generated by Django 5.2 on 2025-04-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
