# Generated by Django 5.2 on 2025-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='daily_percentage',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roi',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roi',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
