# Generated by Django 5.2 on 2025-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0002_alter_roi_daily_percentage_alter_roi_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='daily_percentage',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='roi',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='roi',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
    ]
