# Generated by Django 5.2 on 2025-04-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0003_alter_roi_daily_percentage_alter_roi_deposit_amount_and_more'),
        ('transaction', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roi_transactions', to='transaction.transaction', verbose_name='Transaction'),
        ),
    ]
